STOP_HOTKEY = "f9"

SHOT_RADIUS = 50
SHOT_FORMAT = "PNG"

MATCH_CONFIDENCE = 0.85
MATCH_SEARCH_RADIUS = 100

KALMAN_PROCESS_NOISE = 1e-2
KALMAN_MEASURE_NOISE = 1e-1
KALMAN_MAX_CONSECUTIVE_MISS = 5

MOUSE_MOVE_INTERVAL_MS = 200